{% set version = "0.4.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xicor
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/XICOR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/XICOR/XICOR_{{ version }}.tar.gz
  sha256: 396c03843f94fa1a37555b91e13185c8f1bb5f20fec958ad6a4bab18b3063a31

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-psychtools
  run:
    - r-base
    - r-psychtools

test:
  commands:
    - $R -e "library('XICOR')"           # [not win]
    - "\"%R%\" -e \"library('XICOR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=XICOR
  license: GPL-3.0-only
  summary: Computes robust association measures that do not presuppose linearity. The xi correlation (xicor) is based on cross correlation between ranked increments. The reference for the methods implemented here is Chatterjee, Sourav (2020) <arXiv:1909.10140> This package includes the Galton peas example.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
